// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXBfzUZDlirM0Z2pEmne13gXS4Fa1WS9Y',
    appId: '1:405289945589:web:abef6259a0b47d05d678bc',
    messagingSenderId: '405289945589',
    projectId: 'task-in-web',
    authDomain: 'task-in-web.firebaseapp.com',
    storageBucket: 'task-in-web.appspot.com',
    measurementId: 'G-03V51YPBTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBphXHjjZgAzuZXPBi18PMgu-MpgR9ayh8',
    appId: '1:405289945589:android:3b78079aeb87573ed678bc',
    messagingSenderId: '405289945589',
    projectId: 'task-in-web',
    storageBucket: 'task-in-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqKpOjeEgnvcq7tYXrIMAJnZJk3Qfy3eE',
    appId: '1:405289945589:ios:d7d88d2ae11ef250d678bc',
    messagingSenderId: '405289945589',
    projectId: 'task-in-web',
    storageBucket: 'task-in-web.appspot.com',
    iosBundleId: 'com.example.webAppTask',
  );
}
